---
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    become: true

- name: Install gnu packages
  ansible.builtin.apt:
    name:
      - gnupg
    state: present
    become: true

- name: Install required Python library (pymongo)
  ansible.builtin.pip:
    name: pymongo==3.13.0
    executable: pip3
    become: true

- name: Install mongodb-org
  ansible.builtin.apt:
    name: mongodb-org
    state: present
    force_apt_get: yes
    dpkg_options: force-confdef,force-confold
    become: true

- name: Fix broken packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    force_apt_get: yes
    dpkg_options: force-confdef,force-confold
    fix_missing: yes
    force: yes
    become: true
