---
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted
    enabled: yes
  become: true

- name: reload postgresql configuration
  systemd:
    name: postgresql
    state: reloaded
    enabled: yes
  become: true
